from django import forms

class EditProfileAdmin(forms.Form):
    
    departments = (("ACCT","Accounting"),
        ("ACCT","Accounting for Finance and Consulting"),
        ("ADEN","ALA: English Concentration"),
        ("ADHS","ALA: History Concentration"),
        #("ALA: Interdisciplinary Studies Concentration","ALA: Interdisciplinary Studies Concentration"),
        ("ADPL","ALA: Philosophy Concentration"),
        ("ADPO","ALA: Political Science Concentration"),
        ("ADSO","ALA: Sociology Concentration"),
        ("ADSB","ALA: Sustainability Concentration"),
        ("AADS","African and African Diaspora Studies"),
        ("HIST","American Heritage"),
        ("PHYS","Applied Physics"), 
        ("APSY","Applied Psychology and Human Development"),
        ("ARTH","Art History"),
        ("CHEM","Biochemistry"),
        ("BIO","Biology"),
        ("BZAN","Business Analytics"),
        ("CHEM","Chemistry"),
        ("CLAS","Classics"),
        ("COMM","Communication"), 
        ("CSCI","Computer Science"),
        ("ADCJ","Criminal and Social Justice"),
        ("ADCY","Cybersecurity"),
        ("ECON","Economics"),
        ("FORM","Elementary Education"),
        ("ENGL","English"), 
        ("ADET","Entrepreneurship"),
        ("EESC","Environmental Geoscience"), 
        ("ENVS","Environmental Studies"), 
        ("FILM","Film Studies"),
        ("MFIN","Finance"),
        ("FREN","French"),
        ("MGMT","General Management"),
        ("EESC","Geological Sciences"),
        ("GERM","German Studies"),
        ("PHCG","Global Public Health and the Common Good"),
        ("SPAN ","Hispanic Studies"),
        ("HIST","History"),
        ("ENGR","Human-Centered Engineering"),
        #("Independent","Independent"),
        ("INTL","International Studies"),
        ("ICSP","Islamic Civilization and Societies"),
        ("ITAL","Italian"),
        ("LING","Linguistics"),
        ("MGMT","Management and Leadership"),
        ("MKTG","Marketing"),
        ("MATH","Mathematics"),
        ("MATH","Mathematics/Computer Science"),
        ("MUSA","Music"),
        ("BIOL","Neuroscience"),
        ("NURS","Nursing"),
        ("MGMT","Operations Management"),
        ("SPAN","Perspectives on Spanish America"),
        ("PHIL ","Philosophy"),
        ("PHYS","Physics"),
        ("POLI","Political Science"),
        ("PSYC","Psychology"),
        ("RLRL","Russian"),
        ("FORM","Secondary Education"),
        ("SLAV","Slavic Studies"),
        ("SOCY","Sociology"),
        ("ARTS","Studio Art"),
        ("THTR","Theatre"),
        ("THEO","Theology"),
        ("EDUC","Transformative Educational Studies"),    
        ("ADBM","WCAS Business"),
        ("ADCO","WCAS Communication"),
        ("ADEC","WCAS Economics"),
        ("ADIT","WCAS Information Systems"),
        ("ADPS","WCAS Psychology") 
    )

    department = forms.ChoiceField(choices=departments, required=True, widget=forms.Select(attrs={"class": "form-select"}))


class EditFormStudent(forms.Form):

    semester_choice = (("Fall", "Fall"), ("Spring", "Spring"))
    year_choice = (("2020", "2020"), ("2021", "2021"), ("2022", "2022"), ("2023", "2023"))
    #majors = forms.Char.Field(max_length=50, required=True, widget=forms.TextInput(attrs={'placeholder': 'Major'}))
    majors_choice = (
        ("", ""),
        ("ACCT","Accounting"),
        ("ACCT","Accounting for Finance and Consulting"),
        ("ADEN","ALA: English Concentration"),
        ("ADHS","ALA: History Concentration"),
        #("ALA: Interdisciplinary Studies Concentration","ALA: Interdisciplinary Studies Concentration"),
        ("ADPL","ALA: Philosophy Concentration"),
        ("ADPO","ALA: Political Science Concentration"),
        ("ADSO","ALA: Sociology Concentration"),
        ("ADSB","ALA: Sustainability Concentration"),
        ("AADS","African and African Diaspora Studies"),
        ("HIST","American Heritage"),
        ("PHYS","Applied Physics"), 
        ("APSY","Applied Psychology and Human Development"),
        ("ARTH","Art History"),
        ("CHEM","Biochemistry"),
        ("BIO","Biology"),
        ("BZAN","Business Analytics"),
        ("CHEM","Chemistry"),
        ("CLAS","Classics"),
        ("COMM","Communication"), 
        ("CSCI","Computer Science"),
        ("ADCJ","Criminal and Social Justice"),
        ("ADCY","Cybersecurity"),
        ("ECON","Economics"),
        ("FORM","Elementary Education"),
        ("ENGL","English"), 
        ("ADET","Entrepreneurship"),
        ("EESC","Environmental Geoscience"), 
        ("ENVS","Environmental Studies"), 
        ("FILM","Film Studies"),
        ("MFIN","Finance"),
        ("FREN","French"),
        ("MGMT","General Management"),
        ("EESC","Geological Sciences"),
        ("GERM","German Studies"),
        ("PHCG","Global Public Health and the Common Good"),
        ("SPAN ","Hispanic Studies"),
        ("HIST","History"),
        ("ENGR","Human-Centered Engineering"),
        #("Independent","Independent"),
        ("INTL","International Studies"),
        ("ICSP","Islamic Civilization and Societies"),
        ("ITAL","Italian"),
        ("LING","Linguistics"),
        ("MGMT","Management and Leadership"),
        ("MKTG","Marketing"),
        ("MATH","Mathematics"),
        ("MATH","Mathematics/Computer Science"),
        ("MUSA","Music"),
        ("BIOL","Neuroscience"),
        ("NURS","Nursing"),
        ("MGMT","Operations Management"),
        ("SPAN","Perspectives on Spanish America"),
        ("PHIL ","Philosophy"),
        ("PHYS","Physics"),
        ("POLI","Political Science"),
        ("PSYC","Psychology"),
        ("RLRL","Russian"),
        ("FORM","Secondary Education"),
        ("SLAV","Slavic Studies"),
        ("SOCY","Sociology"),
        ("ARTS","Studio Art"),
        ("THTR","Theatre"),
        ("THEO","Theology"),
        ("EDUC","Transformative Educational Studies"),    
        ("ADBM","WCAS Business"),
        ("ADCO","WCAS Communication"),
        ("ADEC","WCAS Economics"),
        ("ADIT","WCAS Information Systems"),
        ("ADPS","WCAS Psychology") 
)
   # minors = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'placeholder': 'Minor'}))
    minors_choice = (
        ("", ""),
        ("ACCT","Accounting"),
        ("ACCT","Accounting for Finance & Consulting"),
        ("AADS","African and African Diaspora Studies"),
        ("HIST","American Studies"),
        ("HIST","Ancient Civilization"),
        ("CLAS","Ancient Greek"),
        ("APSY","Applied Psychology & Human Development"), 
        ("NELC","Arabic Studies"), 
        ("ARTH","Art History"), 
        ("EALC","Asian Studies"),
        ("BIOL","Biology"),
        ("THEO","Catholic Studies"),
        ("CHEM","Chemistry"),
        ("EALC","Chinese"),
        ("COMM","Communications"),
        ("CSCI","Computer Science"),
        ("ADCY","Cyberstrategy and Design"), 
        ("CSCI","Data Science"),
        ("UNAS","Design Thinking and Innovation"),
        ("SLAV","East European Studies"),
        ("ECON","Economics"),
        ("THTR","Educational Theater"),
        ("ENGL","English"),
        ("ENSV","Environmental Studies"),
        ("THEO","Faith Peace & Justice"),
        ("FILM","Film Studies"),
        ("MFIN","Finance"),
        ("APSY","Foundations in Education"),
        ("FREN","French"),
        ("EESC","Geological Sciences"),
        ("GERM","German"),
        ("GERM","German Studies"),
        ("PHCG","Global Public Health and the Common Good"),
        ("SPAN","Hispanic Studies"),
        ("HIST","History"),
        ("EDUC","Immigration, Education, and Humanitarian Studies"),
        ("EDUC","Inclusive Education"),
        ("INTL","International Studies"),
        ("HIST","Irish Studies"),
        ("NELC","Islamic Civilization & Societies"),
        ("ITAL","Italian"),
        ("THEO","Jewish Studies"),
        ("JOUR","Journalism"),
        ("CLAS","Latin"),
        ("SPAN","Latin American Studies"),
        ("APSY","Leadership in Higher Education and Community Settings"),
        ("LING","Linguistics"),
        ("MGMT","Management and Leadership"),
        ("MGMT","Managing for Social Impact and Public Good"),
        ("MKTG","Marketing"), 
        ("MATH","Mathematics"),
        ("PHCG","Medical Humanities, Health, and Culture"),
        ("FORM","Middle School Mathematics Teaching"),
        ("MUSA","Music"),
        ("PHIL","Philosophy"),
        ("PHYS","Physics"),
        ("THEO","Religion and Public Life"),
        ("MESA","Research, Evaluation, and Measurement"),
        ("APSY","Restorative and Transformational Justice"),
        ("RLRL","Russian"),
        ("FORM","Secondary Education"),
        ("SOCY","Sociology"),
        ("EDUC","Special Education"),
        ("ARTS","Studio Art"),
        ("EDUC","TELL certificate"),
        ("THTR","Theatre"),
        ("THEO","Theology"),
        ("SOCY","Women's & Gender Studies")
    )
    grad_year = forms.ChoiceField(choices=year_choice, required=True, widget=forms.Select(attrs={'class': 'form-select'}))
    grad_sem = forms.ChoiceField(choices=semester_choice, required=True, widget=forms.Select(attrs={'class': 'form-select'}))
    majors = forms.ChoiceField(choices=majors_choice, required=True, widget=forms.Select(attrs={'class': 'form-select mb-3'}))
    majors_2 = forms.ChoiceField(choices=majors_choice, required=False, widget=forms.Select(attrs={'class': 'form-select'}))
    minors = forms.ChoiceField(choices=minors_choice, required=False, widget=forms.Select(attrs={'class': 'form-select mb-3'}))
    minors_2 = forms.ChoiceField(choices=minors_choice, required=False, widget=forms.Select(attrs={'class': 'form-select'}))
