# Generated by Django 4.2.5 on 2023-12-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=9)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('asynch', models.BooleanField(default=False)),
                ('early_morning', models.BooleanField(default=False)),
                ('late_morning', models.BooleanField(default=False)),
                ('early_afternoon', models.BooleanField(default=False)),
                ('late_afternoon', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('credits', models.CharField(max_length=10)),
                ('lecture', models.BooleanField(default=False)),
                ('discussion', models.BooleanField(default=False)),
                ('lab', models.BooleanField(default=False)),
                ('seminar', models.BooleanField(default=False)),
                ('studio', models.BooleanField(default=False)),
                ('clinical', models.BooleanField(default=False)),
                ('doct_cont', models.BooleanField(default=False)),
                ('field', models.BooleanField(default=False)),
                ('thesis', models.BooleanField(default=False)),
                ('hybrid', models.BooleanField(default=False)),
                ('independ', models.BooleanField(default=False)),
                ('internship', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('online_async', models.BooleanField(default=False)),
                ('online_sync', models.BooleanField(default=False)),
                ('practicum', models.BooleanField(default=False)),
                ('recitation', models.BooleanField(default=False)),
                ('tutorial', models.BooleanField(default=False)),
                ('school', models.CharField(max_length=10)),
                ('instructors', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
