# Generated by Django 4.2.5 on 2023-12-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverallWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=10)),
                ('activity_id', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=50)),
                ('class_name_filter', models.CharField(max_length=50)),
                ('num_watchers', models.IntegerField()),
                ('active_semester', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=10)),
                ('activity_id', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('alert', models.CharField(max_length=50)),
                ('alerted', models.BooleanField(default=False)),
                ('active_semester', models.CharField(max_length=6)),
                ('grad_sem', models.CharField(max_length=15)),
            ],
        ),
    ]
